
import type { Product, Category, BlogPost } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  // Fallback to a default placeholder if image not found to prevent crashes
  return { 
    id: image?.id || 'default', 
    url: image?.imageUrl || 'https://picsum.photos/seed/default/600/400', 
    hint: image?.imageHint || 'digital product' 
  };
};

export const mockProducts: Product[] = [
  {
    id: 'prod-instagram-course',
    name: 'Instagram Growth Mastery Course',
    price: 199.99,
    images: [getImage('prod-instagram-course')],
    category: 'Courses & E-books',
    description: 'Master Instagram growth with this comprehensive course. Learn strategies to grow your audience and engagement.',
    isFeatured: true,
  },
  {
    id: 'prod-graphic-design-bundle',
    name: 'Graphic Design Bundle',
    price: 79.99,
    images: [getImage('prod-graphic-design-bundle')],
    category: 'Templates',
    description: 'A huge collection of graphic design assets, including templates, fonts, and icons.',
    isFeatured: true,
  },
  {
    id: 'prod-ai-reels-fitness',
    name: '500+ AI Fitness Reels Bundle',
    price: 49.99,
    images: [getImage('prod-ai-reels-fitness')],
    category: 'Content Bundles',
    description: 'A massive bundle of 500+ AI-generated fitness reels, perfect for social media content creators.',
    isFeatured: true,
  },
  {
    id: 'prod-adobe-suite',
    name: 'Adobe Premium Software 2024',
    price: 299.99,
    images: [getImage('prod-adobe-suite')],
    category: 'Software & Tools',
    description: 'Get the full suite of Adobe Premium software for 2024. Includes Photoshop, Illustrator, Premiere Pro, and more.',
  },
  {
    id: 'prod-ai-reels-motivation',
    name: '500+ AI Motivational Reels Bundle',
    price: 49.99,
    images: [getImage('prod-ai-reels-motivation')],
    category: 'Content Bundles',
    description: 'Inspire your audience with over 500 motivational reels, generated by AI.',
  },
  {
    id: 'prod-god-reels',
    name: '500+ God Reels Bundle',
    price: 49.99,
    images: [getImage('prod-god-reels')],
    category: 'Content Bundles',
    description: 'A unique collection of 500+ spiritual and religious-themed reels for your social media channels.',
  },
  {
    id: 'prod-kids-worksheet',
    name: '6000+ Kids Activity Worksheets',
    price: 29.99,
    images: [getImage('prod-kids-worksheet')],
    category: 'Templates',
    description: 'Over 6000 printable activity worksheets for kids. Perfect for parents and teachers.',
  },
  {
    id: 'prod-excel-templates',
    name: 'Excel Sheet Templates',
    price: 19.99,
    images: [getImage('prod-excel-templates')],
    category: 'Templates',
    description: 'A collection of powerful and easy-to-use Excel templates for various business and personal needs.',
  },
  {
    id: 'prod-digital-marketing-course',
    name: 'Complete Digital Marketing Course',
    price: 249.99,
    images: [getImage('prod-digital-marketing-course')],
    category: 'Courses & E-books',
    description: 'A-to-Z course on digital marketing, covering SEO, SEM, social media, email marketing, and more.',
  },
   {
    id: 'prod-spoken-english-course',
    name: 'Spoken English Course',
    price: 99.00,
    images: [getImage('prod-spoken-english-course')],
    category: 'Courses & E-books',
    description: 'Improve your spoken English with this comprehensive course.',
  },
  {
    id: 'prod-resume-templates',
    name: 'Resume CV Templates',
    price: 25.00,
    images: [getImage('prod-resume-templates')],
    category: 'Templates',
    description: 'Professionally designed resume and CV templates to help you land your dream job.',
  },
  {
    id: 'prod-chatgpt-prompts',
    name: '999+ Ultimate ChatGPT Prompts',
    price: 39.00,
    images: [getImage('prod-chatgpt-prompts')],
    category: 'Software & Tools',
    description: 'Unlock the full potential of ChatGPT with over 999 copy-and-paste prompts for more than 180 tasks.',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'software-and-tools',
    name: 'Software & Tools',
    image: getImage('cat-software'),
    itemCount: 2
  },
  {
    id: 'courses-and-ebooks',
    name: 'Courses & E-books',
    image: getImage('cat-courses'),
    itemCount: 3
  },
  {
    id: 'templates',
    name: 'Templates',
    image: getImage('cat-templates'),
    itemCount: 4
  },
  {
    id: 'content-bundles',
    name: 'Content Bundles',
    image: getImage('cat-bundles'),
    itemCount: 3
  },
];

export const mockBlogPosts: BlogPost[] = [
    {
        id: '1',
        slug: '10-tips-for-selling-digital-products',
        title: '10 Essential Tips for Selling Your Digital Products',
        excerpt: 'Learn the best strategies to successfully market and sell your digital goods online. From pricing to promotion, we cover it all.',
        content: 'Full blog post content goes here...',
        image: getImage('blog-1'),
        author: 'Jane Doe',
        date: '2024-05-15',
    },
    {
        id: '2',
        slug: 'the-rise-of-the-creator-economy',
        title: 'The Rise of the Creator Economy: A New Era for Creatives',
        excerpt: 'Explore how the creator economy is empowering individuals to monetize their passions and build sustainable businesses.',
        content: 'Full blog post content goes here...',
        image: getImage('blog-2'),
        author: 'John Smith',
        date: '2024-05-10',
    },
    {
        id: '3',
        slug: 'how-to-price-your-digital-products',
        title: 'How to Price Your Digital Products for Maximum Profit',
        excerpt: 'Pricing can be tricky. This guide breaks down different pricing models and helps you find the sweet spot for your products.',
        content: 'Full blog post content goes here...',
        image: getImage('blog-3'),
        author: 'Emily White',
        date: '2024-05-01',
    },
];
